### ISSUE TITLE
Cache support

### ISSUE THREAD

**Issue by azachar** [chronogolf/circleci-update-google-chrome#1]
Hello, do you support circleci caching ? So Chrome is not downloaded each time...

Thanks,
A.

**Comment by olivierbuffon** [comment]
I guess something like this could do what you expect:
```yaml
dependencies:
  cache_directories:
    - google-chrome-stable # relative to the build directory
  pre:
    - if [[ ! -e google-chrome-stable ]]; then curl -s https://raw.githubusercontent.com/chronogolf/circleci-google-chrome/master/use_chrome_stable_version.sh | bash; fi
```
You cache the version of chrome on CircleCI and if you want to upgrade to the latest version just run your build `without cache`.

Hope it helps ;)
